# Generated by Django 6.0 on 2025-12-07 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='users.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('red', 'Red'), ('purple', 'Purple'), ('pink', 'Pink'), ('orange', 'Orange'), ('teal', 'Teal'), ('indigo', 'Indigo')], default='green', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'parent')},
        ),
    ]
